// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqWhtKDqkL1W5kmcm6lWn4J-NqhhuurQ',
    appId: '1:661381501523:web:1f933d4280f2d79fb9aca6',
    messagingSenderId: '661381501523',
    projectId: 'taskhub-rst',
    authDomain: 'taskhub-rst.firebaseapp.com',
    storageBucket: 'taskhub-rst.appspot.com',
    measurementId: 'G-VT1XLXKK28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_gpQnssAqCQAQGndYSCtYhfn84t-lPs',
    appId: '1:661381501523:android:29f36deed4cdea25b9aca6',
    messagingSenderId: '661381501523',
    projectId: 'taskhub-rst',
    storageBucket: 'taskhub-rst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OwLTZp7rrkF3jkYhyVVvdRyKRijYyTM',
    appId: '1:661381501523:ios:7108fa64fd57734fb9aca6',
    messagingSenderId: '661381501523',
    projectId: 'taskhub-rst',
    storageBucket: 'taskhub-rst.appspot.com',
    iosClientId: '661381501523-1qm8npdhouim555c7hgp1cmsd0a58lqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OwLTZp7rrkF3jkYhyVVvdRyKRijYyTM',
    appId: '1:661381501523:ios:7108fa64fd57734fb9aca6',
    messagingSenderId: '661381501523',
    projectId: 'taskhub-rst',
    storageBucket: 'taskhub-rst.appspot.com',
    iosClientId: '661381501523-1qm8npdhouim555c7hgp1cmsd0a58lqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdqWhtKDqkL1W5kmcm6lWn4J-NqhhuurQ',
    appId: '1:661381501523:web:04239f8302423675b9aca6',
    messagingSenderId: '661381501523',
    projectId: 'taskhub-rst',
    authDomain: 'taskhub-rst.firebaseapp.com',
    storageBucket: 'taskhub-rst.appspot.com',
    measurementId: 'G-BMX2CWXV3Q',
  );

}